language: android
jdk:
  - oraclejdk8
sudo: false
android:
  components:
  - tools
  - platform-tools
  - build-tools-26.0.1
  - android-26
  licenses:
  - android-sdk-license-.+
script:
- "./gradlew build check --daemon"
after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"
